//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kzu.NuGetReferences.Properties
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kzu.NuGetReferences.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Executing Command).
        /// </summary>
        internal static string ExecutingCommand {
            get {
                return ResourceManager.GetString("ExecutingCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load NuGet Package Manager. Please contact support..
        /// </summary>
        internal static string FailedToLoadNuGetPackage {
            get {
                return ResourceManager.GetString("FailedToLoadNuGetPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your currently installed version of NuGet Package Manager is version {installedVersion}, but the {productName} extension was tested with version {buildVersion}. Some functionality may not work as expected..
        /// </summary>
        internal static string IncompatibleNuGet {
            get {
                return ResourceManager.GetString("IncompatibleNuGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Initializing NuGet Console).
        /// </summary>
        internal static string InitializingConsole {
            get {
                return ResourceManager.GetString("InitializingConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing DevStore version {version} from {vsixPath}..
        /// </summary>
        internal static string Package_DevStoreInstalling {
            get {
                return ResourceManager.GetString("Package_DevStoreInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DevStore is currently not installed..
        /// </summary>
        internal static string Package_DevStoreNotInstalled {
            get {
                return ResourceManager.GetString("Package_DevStoreNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed DevStore version is {oldVersion}. Upgrading to {newVersion}..
        /// </summary>
        internal static string Package_DevStoreOldVersion {
            get {
                return ResourceManager.GetString("Package_DevStoreOldVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest version of DevStore will be activated on your next Visual Studio restart..
        /// </summary>
        internal static string Package_DevStoreRestartNeeded {
            get {
                return ResourceManager.GetString("Package_DevStoreRestartNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find DevStore installer at {vsixPath}. Please reinstall {product}..
        /// </summary>
        internal static string Package_DevStoreVsixNotFound {
            get {
                return ResourceManager.GetString("Package_DevStoreVsixNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying current version of DevStore.
        /// </summary>
        internal static string Package_VerifyingDevStore {
            get {
                return ResourceManager.GetString("Package_VerifyingDevStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package authors..
        /// </summary>
        internal static string PackageInfo_Authors_Description {
            get {
                return ResourceManager.GetString("PackageInfo_Authors_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        internal static string PackageInfo_Authors_DisplayName {
            get {
                return ResourceManager.GetString("PackageInfo_Authors_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string PackageInfo_Category {
            get {
                return ResourceManager.GetString("PackageInfo_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NuGet Package.
        /// </summary>
        internal static string PackageInfo_DisplayName {
            get {
                return ResourceManager.GetString("PackageInfo_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package identifier..
        /// </summary>
        internal static string PackageInfo_Id_Description {
            get {
                return ResourceManager.GetString("PackageInfo_Id_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string PackageInfo_Id_DisplayName {
            get {
                return ResourceManager.GetString("PackageInfo_Id_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package installation location..
        /// </summary>
        internal static string PackageInfo_InstallPath_Description {
            get {
                return ResourceManager.GetString("PackageInfo_InstallPath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Path.
        /// </summary>
        internal static string PackageInfo_InstallPath_DisplayName {
            get {
                return ResourceManager.GetString("PackageInfo_InstallPath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package title..
        /// </summary>
        internal static string PackageInfo_Title_Description {
            get {
                return ResourceManager.GetString("PackageInfo_Title_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string PackageInfo_Title_DisplayName {
            get {
                return ResourceManager.GetString("PackageInfo_Title_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package version..
        /// </summary>
        internal static string PackageInfo_Version_Description {
            get {
                return ResourceManager.GetString("PackageInfo_Version_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string PackageInfo_Version_DisplayName {
            get {
                return ResourceManager.GetString("PackageInfo_Version_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        internal static string Uninstall_Text {
            get {
                return ResourceManager.GetString("Uninstall_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update_Text {
            get {
                return ResourceManager.GetString("Update_Text", resourceCulture);
            }
        }
    }
}
