#region Apache Licensed
/*
 Copyright 2013 Daniel Cazzulino

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
#endregion

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Kzu.NuGetReferences.Properties
{

    ///	<summary>
	///	Provides access to string resources.
	///	</summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("TextTemplate", "1.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	static partial class ResourceNames
	{
		/// <summary>
		/// Resource name for a localized string similar to: 
		///	"(Executing Command)"
		/// </summary>
		public const string ExecutingCommand = "ExecutingCommand";
	
		/// <summary>
		/// Resource name for a localized string similar to: 
		///	"Failed to load NuGet Package Manager. Please contact support."
		/// </summary>
		public const string FailedToLoadNuGetPackage = "FailedToLoadNuGetPackage";
	
		/// <summary>
		/// Resource name for a localized string similar to: 
		///	"Your currently installed version of NuGet Package Manager is version {installedVersion}, but the {productName} extension was tested with version {buildVersion}. Some functionality may not work as expected."
		/// </summary>
		public const string IncompatibleNuGet = "IncompatibleNuGet";
	
		/// <summary>
		/// Resource name for a localized string similar to: 
		///	"(Initializing NuGet Console)"
		/// </summary>
		public const string InitializingConsole = "InitializingConsole";
		
		///	<summary>
		///	Provides access to string resources.
		///	</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("TextTemplate", "1.0")]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public static partial class PackageInfo
		{
			/// <summary>
			/// Resource name for a localized string similar to: 
			///	"General"
			/// </summary>
			public const string Category = "PackageInfo_Category";
		
			/// <summary>
			/// Resource name for a localized string similar to: 
			///	"NuGet Package"
			/// </summary>
			public const string DisplayName = "PackageInfo_DisplayName";
			
			///	<summary>
			///	Provides access to string resources.
			///	</summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("TextTemplate", "1.0")]
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
			public static partial class Id
			{
				/// <summary>
				/// Resource name for a localized string similar to: 
				///	"Package identifier."
				/// </summary>
				public const string Description = "PackageInfo_Id_Description";
			
				/// <summary>
				/// Resource name for a localized string similar to: 
				///	"Id"
				/// </summary>
				public const string DisplayName = "PackageInfo_Id_DisplayName";
			}
			
			///	<summary>
			///	Provides access to string resources.
			///	</summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("TextTemplate", "1.0")]
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
			public static partial class Version
			{
				/// <summary>
				/// Resource name for a localized string similar to: 
				///	"Package version."
				/// </summary>
				public const string Description = "PackageInfo_Version_Description";
			
				/// <summary>
				/// Resource name for a localized string similar to: 
				///	"Version"
				/// </summary>
				public const string DisplayName = "PackageInfo_Version_DisplayName";
			}
			
			///	<summary>
			///	Provides access to string resources.
			///	</summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("TextTemplate", "1.0")]
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
			public static partial class Title
			{
				/// <summary>
				/// Resource name for a localized string similar to: 
				///	"Package title."
				/// </summary>
				public const string Description = "PackageInfo_Title_Description";
			
				/// <summary>
				/// Resource name for a localized string similar to: 
				///	"Title"
				/// </summary>
				public const string DisplayName = "PackageInfo_Title_DisplayName";
			}
			
			///	<summary>
			///	Provides access to string resources.
			///	</summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("TextTemplate", "1.0")]
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
			public static partial class Authors
			{
				/// <summary>
				/// Resource name for a localized string similar to: 
				///	"Package authors."
				/// </summary>
				public const string Description = "PackageInfo_Authors_Description";
			
				/// <summary>
				/// Resource name for a localized string similar to: 
				///	"Authors"
				/// </summary>
				public const string DisplayName = "PackageInfo_Authors_DisplayName";
			}
			
			///	<summary>
			///	Provides access to string resources.
			///	</summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("TextTemplate", "1.0")]
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
			public static partial class InstallPath
			{
				/// <summary>
				/// Resource name for a localized string similar to: 
				///	"Package installation location."
				/// </summary>
				public const string Description = "PackageInfo_InstallPath_Description";
			
				/// <summary>
				/// Resource name for a localized string similar to: 
				///	"Install Path"
				/// </summary>
				public const string DisplayName = "PackageInfo_InstallPath_DisplayName";
			}
		}
		
		///	<summary>
		///	Provides access to string resources.
		///	</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("TextTemplate", "1.0")]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public static partial class Uninstall
		{
			/// <summary>
			/// Resource name for a localized string similar to: 
			///	"Uninstall"
			/// </summary>
			public const string Text = "Uninstall_Text";
		}
		
		///	<summary>
		///	Provides access to string resources.
		///	</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("TextTemplate", "1.0")]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public static partial class Update
		{
			/// <summary>
			/// Resource name for a localized string similar to: 
			///	"Update"
			/// </summary>
			public const string Text = "Update_Text";
		}
		
		///	<summary>
		///	Provides access to string resources.
		///	</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("TextTemplate", "1.0")]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public static partial class Package
		{
			/// <summary>
			/// Resource name for a localized string similar to: 
			///	"Installing DevStore version {version} from {vsixPath}."
			/// </summary>
			public const string DevStoreInstalling = "Package_DevStoreInstalling";
		
			/// <summary>
			/// Resource name for a localized string similar to: 
			///	"DevStore is currently not installed."
			/// </summary>
			public const string DevStoreNotInstalled = "Package_DevStoreNotInstalled";
		
			/// <summary>
			/// Resource name for a localized string similar to: 
			///	"Installed DevStore version is {oldVersion}. Upgrading to {newVersion}."
			/// </summary>
			public const string DevStoreOldVersion = "Package_DevStoreOldVersion";
		
			/// <summary>
			/// Resource name for a localized string similar to: 
			///	"Could not find DevStore installer at {vsixPath}. Please reinstall {product}."
			/// </summary>
			public const string DevStoreVsixNotFound = "Package_DevStoreVsixNotFound";
		
			/// <summary>
			/// Resource name for a localized string similar to: 
			///	"Verifying current version of DevStore"
			/// </summary>
			public const string VerifyingDevStore = "Package_VerifyingDevStore";
		}
	}
}
