//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Globalization;

namespace ClariusLabs.NuGetReferences.Properties
{
	///	<summary>
	///	Provides access to string resources.
	///	</summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("netfx-System.Strings", "1.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	static partial class Strings
	{
		/// <summary>
		/// Looks up a localized string similar to: 
		///	(Executing Command)
		/// </summary>
		public static string ExecutingCommand { get { return Resources.ExecutingCommand; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Failed to load NuGet Package Manager. Please contact support.
		/// </summary>
		public static string FailedToLoadNuGetPackage { get { return Resources.FailedToLoadNuGetPackage; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Your currently installed version of NuGet Package Manager is version {installedVersion}, but the {productName} extension was tested with version {buildVersion}. Some functionality may not work as expected.
		/// </summary>
		public static string IncompatibleNuGet(object installedVersion, object productName, object buildVersion)
		{
			return Resources.IncompatibleNuGet.FormatWith(new 
			{
				installedVersion = installedVersion,
				productName = productName,
				buildVersion = buildVersion,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	(Initializing NuGet Console)
		/// </summary>
		public static string InitializingConsole { get { return Resources.InitializingConsole; } }
		
		///	<summary>
		///	Provides access to string resources.
		///	</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("netfx-System.Strings", "1.0.0.0")]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public static partial class Uninstall
		{
			/// <summary>
			/// Looks up a localized string similar to: 
			///	Uninstall
			/// </summary>
			public static string Text { get { return Resources.Uninstall_Text; } }
		}
		
		///	<summary>
		///	Provides access to string resources.
		///	</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("netfx-System.Strings", "1.0.0.0")]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public static partial class Update
		{
			/// <summary>
			/// Looks up a localized string similar to: 
			///	Update
			/// </summary>
			public static string Text { get { return Resources.Update_Text; } }
		}
	}
}

